//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perscription
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorRecep
    {
        public int IdReceiptNo { get; set; }
        public Nullable<long> ReceiptNumber { get; set; }
        public string ReceiptType { get; set; }
        public string ReceiptCat { get; set; }
        public int IdDoctor { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Perscript Perscript { get; set; }
    }
}
