//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perscription
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Psychotrop = false;
            this.Senior = false;
            this.Vaccine = false;
            this.Used = false;
            this.Perscript = new HashSet<Perscript>();
            this.Level = new HashSet<Level>();
        }
    
        public int BL7 { get; set; }
        public long EAN { get; set; }
        public bool Psychotrop { get; set; }
        public bool Senior { get; set; }
        public bool Vaccine { get; set; }
        public decimal Cost { get; set; }
        public string Name { get; set; }
        public string NameInt { get; set; }
        public string Form { get; set; }
        public string Dose { get; set; }
        public string Wrapping { get; set; }
        public bool Used { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perscript> Perscript { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Level> Level { get; set; }
    }
}
